# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tictactoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 513)
        Dialog.setStyleSheet("background-color: rgb(204, 227, 222);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 110, 101, 91))
        self.pushButton.setStyleSheet("background-color: None;font:40pt ;\n"
"color: rgb(131, 131, 131);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 110, 101, 91))
        self.pushButton_2.setStyleSheet("background-color: None;font:40pt ;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 110, 101, 91))
        self.pushButton_3.setStyleSheet("background-color: None;font:40pt ;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 200, 101, 91))
        self.pushButton_5.setStyleSheet("font:40pt ;\n"
"color: rgb(131, 131, 131);background-color: None;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 200, 101, 91))
        self.pushButton_6.setStyleSheet("font:40pt ;\n"
"background-color: None;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(330, 290, 101, 91))
        self.pushButton_9.setStyleSheet("font:40pt ;\n"
"background-color: None;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 290, 101, 91))
        self.pushButton_8.setStyleSheet("font:40pt ;\n"
"background-color: None;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 290, 101, 91))
        self.pushButton_7.setStyleSheet("font:40pt ;\n"
"background-color: None;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 200, 101, 91))
        self.pushButton_4.setStyleSheet("background-color: None;font:40pt ;\n"
"color: rgb(131, 131, 131);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(106, 40, 91, 20))
        self.label.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 40, 91, 20))
        self.label_2.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"text-decoration: underline;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 400, 361, 41))
        self.label_3.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 460, 101, 41))
        self.pushButton_10.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("tictactoe", "TicTacToe"))
        self.label.setText(_translate("Dialog", "Player1 :\'X\'"))
        self.label_2.setText(_translate("Dialog", "Player2 :\'O\'"))
        self.label_3.setText(_translate("Dialog", "Player1\'s turn"))
        self.pushButton_10.setText(_translate("Dialog", "Reset"))
